<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IndustrialGateway.Core\IndustrialGateway.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Modbus TCP -->
    <PackageReference Include="NModbus" Version="3.0.72" />

    <!-- OPC UA -->
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" Version="1.5.374.54" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.374.54" />

    <!-- MQTT -->
    <PackageReference Include="MQTTnet" Version="4.3.3.952" />

    <!-- Logging -->
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>
